### ISSUE TITLE
Error "The model: `gpt-4` does not exist"

### ISSUE THREAD

**Issue by ChristianWeyer** [corca-ai/EVAL#14]
The following call
`http POST http://localhost:8000/command key=1 files:=\[\] query="Hey there!"`

produces this:

```
HTTP/1.1 200 OK
content-length: 59
content-type: application/json
date: Wed, 05 Apr 2023 16:11:59 GMT
server: uvicorn

{
    "files": [],
    "response": "The model: `gpt-4` does not exist"
}
```

Am I missing some config, maybe?

**Comment by hanchchch** [comment]
It might because you don't have access to `gpt-4` on OpenAI API. Try using `gpt-3.5-turbo` by change line 118 of core/agents/llm.py.

```python
    model_name: str = "gpt-3.5-turbo"
```

I think I should make it to use env var so we can change it without changing the code.

**Comment by ChristianWeyer** [comment]
How would one get access to `gpt-4` via the API?

**Comment by ChristianWeyer** [comment]
Ah... 🙂
https://openai.com/waitlist/gpt-4-api

**Comment by ChristianWeyer** [comment]
Yes!
