### ISSUE TITLE
How do I remove or shut down an app created by EVAL?

### ISSUE THREAD

**Issue by cvarrichio** [corca-ai/EVAL#17]
I tried a standard "To Do" prompt and it successfully created that app.  However, I can't figure out a way to shut down that app.  If I kill the docker environment and restart it, it appears to restart the to do app as well.

**Comment by cvarrichio** [comment]
I may be misunderstanding what is going on here.  I'll do more investigation.

**Comment by hanchchch** [comment]
fyi, if you restart the docker envs (maybe with `docker-compose down`) the processes it created should be also killed. But the ports may still seems to be allocated since it's binded by `ports` option in `docker-compose.yml`, despite there's no process running on it.
