### ISSUE TITLE
Bind for 0.0.0.0:8000 failed: port is already allocated

### ISSUE THREAD

**Issue by magick93** [corca-ai/EVAL#20]
I keep getting the following error:

```
Error response from daemon: driver failed programming external connectivity on endpoint eval.gpu (260097999e8823c48153d3037a64c28d39973bc219dd9af055eb56dbdc280e24): Bind for 0.0.0.0:8000 failed: port is already allocated
```

However, I dont have anything running on port 8000. `lsof -i :8000` does not return a result.

Also, I have set in the `.env` file - `USE_GPU=False` yet it still seems, at least based on the above, to be trying to use the gpu.

**Comment by hanchchch** [comment]
docker-compose.yml has 2 services, one with gpu and one without it. If you just run `docker-compose up` it would try to serve both and cause this problem. We updated about this on README.md few days ago so please refer it!

**Comment by magick93** [comment]
Awesome!
My apologies for not reading carefully enough.
