### ISSUE TITLE
The model 'gpt-4' does not exist

### ISSUE THREAD

**Issue by usersink** [corca-ai/EVAL#21]
Using eval without gpu and submitting any command from the terminal:

`curl -X POST -H "Content-Type: application/json" -d '{"key": "sessionid", "files": ["https://example.com/image.png"], "query": "Hi there!"}' http://localhost:8000/command`

Response:

`{"response":"The model: `gpt-4` does not exist","files":[]}`

For those without access to gpt-4, can this be modified to use another model in the interim?

**Comment by hanchchch** [comment]
duplicates #14 
We are planning to make it as environment variable.

**Comment by usersink** [comment]
Thank you! Still new to git. I'll be sure to look through closed issues in future.

**Comment by hanchchch** [comment]
no worries, I'm just thankful that you have interest in this project and report your issue! so we can add new feature like #22 . Thanks!
