### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by cvarrichio** [corca-ai/EVAL#25]
With the latest version, I've started to receive the following error with each request:

eval        | INFO:     Waiting for application startup.
eval        | INFO:     Application startup complete.
eval        | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
eval        | INFO:     172.18.0.1:46550 - "POST /command HTTP/1.1" 404 Not Found
eval        | INFO:     172.18.0.1:56596 - "POST /command HTTP/1.1" 404 Not Found
eval        | INFO:     172.18.0.1:54216 - "POST /command HTTP/1.1" 404 Not Found
eval        | INFO:     172.18.0.1:42932 - "POST /command HTTP/1.1" 404 Not Found
eval        | INFO:     172.18.0.1:42136 - "POST /command HTTP/1.1" 404 Not Found

On the client side, I'm simply getting the message:
`{"detail":"Not Found"}`

Sample prompt:
curl -X POST -H "Content-Type: application/json" -d '{"key": "sessionid", "files": [], "query": "Please develop and serve a simple web TODO app. The user can list all TODO items and add, delete each TODO item. I want it to have neuromorphism-style. The ports you can use are 4000 and 7000. Cannot use PORT variable in environment."}' http://localhost:8000/command

**Comment by hanchchch** [comment]
Hi! Sorry for inconvenience, we just updated the endpoint to distinguish between web pages and execution apis. https://github.com/corca-ai/EVAL#3-send-request-to-eval

I didn't expect someone would it use it this soon 😅 I mean no one knew this project just 2 days ago 😂 Sorry again, we'll write release note next time if there's significant changes like this.

**Comment by cvarrichio** [comment]
Thanks for the quick response.  I'm still unclear what is different now.  If I used the exact command from your link I receive the same error:
curl -X POST -H "Content-Type: application/json" -d '{"session": "sessionid", "files": ["https://example.com/image.png"], "prompt": "Hi there!"}' http://localhost:8000/command

**Comment by adldotori** [comment]
You have two options:
1. ```curl -X POST -H "Content-Type: application/json" -d '{"session": "sessionid", "files": [], "prompt": "Hi there!"}' http://localhost:8000/api/execute```
2. connect to localhost:8000 and send your request using GUI.
![image](https://user-images.githubusercontent.com/19206046/230646503-43525948-7698-4035-a473-376cd599c4a1.png)
![image](https://user-images.githubusercontent.com/19206046/230646579-fada2163-085c-434a-93c9-fcf19f44de86.png)

**Comment by hanchchch** [comment]
> Thanks for the quick response. I'm still unclear what is different now. If I used the exact command from your link I receive the same error: curl -X POST -H "Content-Type: application/json" -d '{"session": "sessionid", "files": ["https://example.com/image.png"], "prompt": "Hi there!"}' http://localhost:8000/command

Your url should be http://localhost:8000/api/execute, not http://localhost:8000/command.

**Comment by cvarrichio** [comment]
Problem solved, you can close this issue.
