### ISSUE TITLE
Terminal unterminated quoted string

### ISSUE THREAD

**Issue by cvarrichio** [corca-ai/EVAL#32]
I've been receiving this error repeatedly with my recent queries:

eval        | Action: Terminal
eval        | Input: find Auto-GPT-master -type f -name "*.py"
eval        | Realtime Terminal Output:
eval        | stderr /bin/sh: 1: Syntax error: Unterminated quoted string
eval        | Observation: /bin/sh: 1: Syntax error: Unterminated quoted string

The agent will then simply repeat this step over and over, because it is the correct step.  That is a valid bash command.  But for some reason it is getting a syntax error.  I am guessing that the terminal command is losing the closing quote for some reason.

**Comment by hanchchch** [comment]
Thanks for sharing. We'll take a look on it

**Comment by cvarrichio** [comment]
Receiving a similar variation now.  This time, the close quote is explicitly omitted in the log:

eval        | Input: find EVAL -type f -iname "*.py
eval        | Realtime Terminal Output:
eval        | stderr /bin/sh: 1: Syntax error: Unterminated quoted string
eval        | Observation: /bin/sh: 1: Syntax error: Unterminated quoted string
