### ISSUE TITLE
Control Center use the port 7000 on mac 13.1

### ISSUE THREAD

**Issue by zkhCreator** [corca-ai/EVAL#35]
**Describe the bug**
Control Center use the port 7000 on mac 13.1. 

**Screenshots**
<img width="725" alt="image" src="https://user-images.githubusercontent.com/12930558/230719610-279f61f8-01d3-4b71-ba81-c15aa7ac03e1.png">

**Desktop (please complete the following information):**
 - OS: mac 13.1

**Comment by adldotori** [comment]
Thank you for sharing this issue. We'll fix that problem by changing the port from 7000 to 6500. Before fixing, you can solve this problem by changing docker-compose.yml and your user prompt.

**Comment by zkhCreator** [comment]
Ok. Dont forget to change example. maybe I can pull reqeusts to fix it?

**Comment by adldotori** [comment]
I would appreciate it if you open a pull request! Thank you very much.

**Comment by zkhCreator** [comment]
fixed on #36
