### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'file://d3_app/index.html'

### ISSUE THREAD

**Issue by cvarrichio** [corca-ai/EVAL#37]
I've been receiving errors like this quite frequently.  Sometimes the structure of the error is 
No such file or directory: 'file/d3_app/index.html'

I also am seeing EVAL frequently hallucinate creating files - I can see the code for the file in the server console, but the file is not actually created.

In general I think there may be something wrong with the file creation and reference process.

eval        |   File "/app/core/upload/static.py", line 27, in upload
eval        |     shutil.copy(filepath, file_path)
eval        |   File "/usr/local/lib/python3.10/shutil.py", line 417, in copy
eval        |     copyfile(src, dst, follow_symlinks=follow_symlinks)
eval        |   File "/usr/local/lib/python3.10/shutil.py", line 254, in copyfile
eval        |     with open(src, 'rb') as fsrc:
eval        | FileNotFoundError: [Errno 2] No such file or directory: 'file://d3_app/index.html'

And

eval        |   File "/app/core/upload/static.py", line 27, in upload
eval        |     shutil.copy(filepath, file_path)
eval        |   File "/usr/local/lib/python3.10/shutil.py", line 417, in copy
eval        |     copyfile(src, dst, follow_symlinks=follow_symlinks)
eval        |   File "/usr/local/lib/python3.10/shutil.py", line 254, in copyfil                         e
eval        |     with open(src, 'rb') as fsrc:
eval        | FileNotFoundError: [Errno 2] No such file or directory: 'file/webapp.html'

**Comment by hanchchch** [comment]
Thank you for reporting!

1. file reference process - there was a huge issue on here! I can fix it fast and will upload PR soon.
2. file creation - all generated files should be stored in `./playground` dir. Have you checked there?
