### ISSUE TITLE
Trying to run without GPU doesn't compile, somehow wants dependencies that are for GPU only

### ISSUE THREAD

**Issue by cwwmbm** [corca-ai/EVAL#40]
1. Running docker-compose up --build eval
2. Getting the following error in the terminal:
[+] Running 1/1 ✔ Container eval  Recreated                                                                                                                                                                                      0.1s Attaching to eval
eval  | Traceback (most recent call last):
eval  |   File "<string>", line 1, in <module>
eval  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
eval  |     return _bootstrap._gcd_import(name[level:], package, level)
eval  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
eval  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
eval  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
eval  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
eval  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
eval  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
eval  |   File "/app/api/main.py", line 46, in <module>
eval  |     import torch
eval  | ModuleNotFoundError: No module named 'torch'
eval exited with code 1

So torch is missing. Going into pyproject.toml file and seeing that torch is under optional GPU-only dependencies:
[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.94.1"
langchain = "^0.0.115"
diffusers = "^0.14.0"
pydantic = "^1.10.6"
tenacity = "^8.2.2"
llama-index = "0.4.29"
python-dotenv = "^1.0.0"
pillow = "^9.4.0"
boto3 = "^1.26.94"
uvicorn = "^0.21.1"
python-ptrace = "^0.9.8"
jinja2 = "^3.1.2"
python-multipart = "^0.0.6"
[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = "^2.0.0"
transformers = {git = "https://github.com/huggingface/transformers.git", rev = "main"}
accelerate = "^0.17.1"
sentencepiece = "^0.1.97"
bitsandbytes = "^0.37.2"

Moving torch under [tool.poetry.dependencies] passes the step and then fails saying missing transformers, which is again under GPU dependencies.

**Comment by adldotori** [comment]
Can you retry this? Maybe this problem may have been solved

**Comment by cwwmbm** [comment]
So I ended up moving torch and transformers under [tool.poetry.dependencies] and after that it executed just fine! I don't know if this is somehow specific to Apple silicone chip thing or something else, but I got it working in the end.

One thing (unrelated to this) is that it definitely wasn't performing as shown in the demo. I even copied the prompt word by word (about building TODO app) and it only created js file, and even that was incomplete. I'm guessing the problem is that I don't have gpt-4 API access so had to settle for 3.5-turbo. It is still an incredible tool for sure, and once I get GTP-4 I think its power will be on full display.

**Comment by adldotori** [comment]
EVAL is heavily affected by the version of model. I think that the main reason is the difference between gpt-3.5 and gpt-4, too. We will further improve EVAL through various ideas. Then the performance of the model will be less affected. Please wait a little bit.
