### ISSUE TITLE
Risks ⚠️

### ISSUE THREAD

**Issue by Abeansits** [corca-ai/EVAL#50]
Hello @adldotori and others! 
I appreciate the effort and innovation behind this project. However, I'd like to express my concerns regarding the potential risks associated with allowing AI agents to run arbitrary code. This feature could lead to unintended consequences, such as security vulnerabilities, unauthorized access to sensitive data, or the creation of harmful applications. I encourage the developers to consider the ethical implications and potential dangers of this functionality, and to adopt best practices in AI safety and security to protect users and the wider community. Thank you for your attention to this matter.

**Comment by MikeKMiller** [comment]
I appreciate your concerns about the potential risks of allowing AI agents to run arbitrary code, and I understand the importance of implementing safety measures to protect users and the wider community. However, I believe that safety is more the responsibility of the user, and simply staying away from cutting-edge technology out of fear can limit innovation.

Advancements in technology require us to embrace the unknown and explore new possibilities. By entrusting users with the responsibility of using AI agents safely and ethically, we can empower them to push the boundaries of what is possible while still being mindful of potential risks. 

Additionally, educating users on best practices and the ethical implications of new technologies can help ensure that they make informed decisions when utilizing these powerful tools.

In conclusion, while we should be cautious and attentive to the potential dangers associated with new technologies, we must also trust in the user's ability to navigate these risks responsibly. By doing so, we can continue to foster innovation and unlock the full potential of AI agents, without sacrificing safety or ethical considerations.

**Comment by Abeansits** [comment]
Thanks for your reply Mike! I agree that users have a big role in using AI responsibly, and education is super important. But, I think developers and the AI community also share this responsibility.

We need to create AI systems with safety measures to prevent misuse and bad outcomes. By working together with others in the AI community, we can make AI safer and more responsible.

I've seen many people with software dev experience start using these tools, but they might not have the necessary knowledge or feel the same about AI safety. Finding the balance between innovation and safety can be tough, but it's crucial to make sure AI benefits everyone without causing harm.

Let's collaborate to build a future where AI can flourish without sacrificing safety or ethics. Is there anything I can do to help promote safety and awareness in your project?

**Comment by adldotori** [comment]
Thanks for productive discussion @Abeansits @MikeKMiller ! I and @hanchchch are concerned about the same topic. If EVAL turns evil, it can remove all the files on your computer. So, we recommend running EVAL in docker. Other than that, just in my opinion, there is nothing else EVAL can attack something. Of course, when we test it, we assume it's always nice, and we don't say anything bad, so we don't know what it could do exactly. If you're interested, we'd love to have you test EVAL to behave as EVIL as possible.

**Comment by adldotori** [comment]
If you want to contribute EVAL more, both of you can join our discord and talk us.
