### ISSUE TITLE
Unable to use GPT-4 model with EVAL

### ISSUE THREAD

**Issue by kkilatesGPT** [corca-ai/EVAL#51]
Hello,

I am trying to use the GPT-4 model with EVAL, but I am encountering an issue. Although my OpenAI account has access to GPT-4 and the API key works correctly in other applications, I am unable to get EVAL to work with GPT-4.

Here's a summary of the steps I have taken:

I have cloned the EVAL repository and set up the project with Docker.
I have added my OpenAI API key to the .env file.
I have confirmed that the MODEL_NAME variable in the env.py file is set to gpt-4 by default.
Despite these steps, EVAL keeps giving me an error message stating that the GPT-4 model does not exist. I have tried using a different API key, updating the .env file, and restarting the Docker container, but the issue persists.

Could you please provide some guidance on how to resolve this issue or let me know if there's a problem with the EVAL project itself? I would appreciate any help you can offer.

Thank you!

![Captura de Pantalla 2023-04-25 a las 18 51 42](https://user-images.githubusercontent.com/131761976/234347799-b6dedc4d-8083-4067-b3aa-eeb4b9e7245f.png)

**Comment by adldotori** [comment]
What is the result when you try gpt-3.5-turbo? I don't know the reason not yet.
If your key is wrong, "Incorrect API key provided" error will occur. So, I think your key is right and it hasn't GPT-4 acess.

**Comment by kkilatesGPT** [comment]
Thank you for your prompt response. I have tried using gpt-3.5-turbo and it works perfectly fine. I appreciate your insight that the "Incorrect API key provided" error would occur if the key is wrong, and I believe my key is correct. I understand that the results with GPT-4 would be even better, but I am satisfied with the performance of gpt-3.5-turbo for now.

I will continue to investigate if the issue is caused by my API key, which is a very likely possibility. I would like to express my appreciation for your project and the hard work you have put into it.
